// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkQvERngjE-BhEZpfuSgvAQpyPWPst-7g',
    appId: '1:930101232549:web:4a0c6e160077a7305bde4c',
    messagingSenderId: '930101232549',
    projectId: 'msg-attendance-3f2bc',
    authDomain: 'msg-attendance-3f2bc.firebaseapp.com',
    storageBucket: 'msg-attendance-3f2bc.appspot.com',
    measurementId: 'G-FBY0V295W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlx2YBDkLLPOqUTiaqINwiH-89SrZIv8M',
    appId: '1:930101232549:android:405f2632243d53245bde4c',
    messagingSenderId: '930101232549',
    projectId: 'msg-attendance-3f2bc',
    storageBucket: 'msg-attendance-3f2bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW-tTnfSOoO3Bk9cL7VeEu-2CPf7KKPzo',
    appId: '1:930101232549:ios:19e42a45d6e5b5165bde4c',
    messagingSenderId: '930101232549',
    projectId: 'msg-attendance-3f2bc',
    storageBucket: 'msg-attendance-3f2bc.appspot.com',
    iosClientId: '930101232549-brg0ve5vltagh255p7v13mi1f8aujqss.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );
}
